const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const repo=path.join(__dirname,'../..');
const xaml=fs.readFileSync(path.join(repo,'desktop_windows/MainWindow.xaml'),'utf8');
const code=fs.readFileSync(path.join(repo,'desktop_windows/MainWindow.xaml.cs'),'utf8');
const app=fs.readFileSync(path.join(repo,'android_src/app/src/main/assets/app.js'),'utf8');
assert.match(xaml,/x:Name="HomeButton"[^>]+Click="Home_Click"/);
assert.match(xaml,/PreviewMouseWheel="Browser_PreviewMouseWheel"/);
assert.match(code,/ExecuteScriptAsync\("Boolean\(window\.portalBack && window\.portalBack\(\)\)"\)/);
assert.match(code,/ExecuteScriptAsync\("Boolean\(window\.portalHome && window\.portalHome\(\)\)"\)/);
assert.match(code,/window\.scrollBy\(\{\{top:/);
assert.match(code,/ProcessFailed[\s\S]+_webRecoveryPending[\s\S]+Browser\.Reload\(\)/);
assert.match(app,/window\.portalBack=/);
assert.match(app,/S\.history\.push\(S\.page\)/);
assert.match(app,/window\.portalHome=/);
assert.match(app,/autoCheckUpdates\(\)/);
assert.match(xaml,/Content="Обновить PORTAL"[^>]+Click="CheckUpdate_Click"/);
assert.match(code,/private const int CurrentBuild = 43/);
assert.match(code,/WebViewCompatibilityArguments = "--disable-gpu --disable-gpu-compositing"/);
assert.match(code,/AdditionalBrowserArguments = WebViewCompatibilityArguments/);
assert.match(code,/catch \(HttpRequestException\)[\s\S]+LoadGithubUpdateManifestAsync\(\)/);
assert.match(code,/catch \(TaskCanceledException\)[\s\S]+LoadGithubUpdateManifestAsync\(\)/);
assert.match(code,/if \(_serverOrigin is not null\)[\s\S]+githubManifest = await LoadGithubUpdateManifestAsync\(\)/);
assert.doesNotMatch(code,/Сначала подключитесь к серверу PORTAL/);
assert.match(code,/PORTAL-Desktop\/4\.3\.0/);
assert.match(code,/DownloadAndInstallUpdate\(manifest, downloadUri\)/);
assert.match(code,/PropertyNamingPolicy = JsonNamingPolicy\.SnakeCaseLower/);
assert.match(code,/api\.github\.com\/repos\/\{GithubRepository\}\/releases\?per_page=50/);
assert.match(code,/portal-desktop-v\(\\d\+\)\\\.\(\\d\+\)\\\.0/);
assert.match(code,/AllowedUpdateRedirect\(initial, next\)/);
assert.match(code,/\.githubusercontent\.com/);
assert.match(code,/ZipFile\.OpenRead\(packagePath\)/);
assert.match(code,/SHA-256 пакета обновления не совпадает/);
assert.match(code,/githubManifest\.Build > serverManifest\.Build/);
assert.match(code,/portal-desktop-43-style/);
assert.match(code,/portalDesktop43Patched/);
assert.doesNotMatch(code,/ProbePortalWebAsync/);
assert.match(code,/options\.IsInPrivateModeEnabled = false/);
assert.match(code,/Browser\.Source = new Uri\(origin \+ "\/web\/"\)/);
assert.match(code,/_pendingPersistOrigin = persist \? origin : null/);
assert.match(code,/\['Работа',[\s\S]+\['Управление',[\s\S]+\['Учёт и финансы',[\s\S]+\['Аналитика',[\s\S]+\['Система'/);
assert.match(code,/UpdateDesktopShortcuts\(executable, target, version\)/);
assert.match(code,/Process\.Start\(new ProcessStartInfo\(executable\)/);
console.log('Desktop shell navigation, branding and self-update checks: OK');
