const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const repo=path.join(__dirname,'../..');
const xaml=fs.readFileSync(path.join(repo,'desktop_windows/MainWindow.xaml'),'utf8');
const code=fs.readFileSync(path.join(repo,'desktop_windows/MainWindow.xaml.cs'),'utf8');
const app=fs.readFileSync(path.join(repo,'android_src/app/src/main/assets/app.js'),'utf8');
const index=fs.readFileSync(path.join(repo,'android_src/app/src/main/assets/index.html'),'utf8');
const mascots=fs.readFileSync(path.join(repo,'android_src/app/src/main/assets/desktop_mascots.js'),'utf8');
const cache=fs.readFileSync(path.join(repo,'desktop_windows/DesktopCacheBridge.cs'),'utf8');
const windowsWorkflow=fs.readFileSync(path.join(repo,'.github/workflows/windows-desktop.yml'),'utf8');
const signature=fs.readFileSync(path.join(repo,'desktop_windows/DesktopUpdateSignature.cs'),'utf8');
const messengerWindow=fs.readFileSync(path.join(repo,'desktop_windows/MessengerWindow.xaml.cs'),'utf8');
const messengerXaml=fs.readFileSync(path.join(repo,'desktop_windows/MessengerWindow.xaml'),'utf8');
assert.match(messengerWindow,/https:\/\/web\.telegram\.org\/a\//);
assert.match(messengerWindow,/https:\/\/web\.max\.ru\//);
assert.match(messengerWindow,/MessengerWebView2/);
assert.match(messengerWindow,/IsAllowedProviderUri/);
assert.doesNotMatch(messengerWindow,/portalSession|Bearer|token|companyJson/);
assert.match(messengerXaml,/TelegramTab/);
assert.match(messengerXaml,/MaxTab/);
assert.match(code,/private static MessengerWindow\? _messengerWindow/);
assert.match(code,/OpenMessengerWindowAsync\(string provider/);
assert.match(xaml,/x:Name="HomeButton"[^>]+Click="Home_Click"/);
assert.match(xaml,/PreviewMouseWheel="Browser_PreviewMouseWheel"/);
assert.match(code,/ExecuteScriptAsync\("Boolean\(window\.portalBack && window\.portalBack\(\)\)"\)/);
assert.match(code,/ExecuteScriptAsync\("Boolean\(window\.portalHome && window\.portalHome\(\)\)"\)/);
assert.match(code,/window\.scrollBy\(\{\{top:/);
assert.match(index,/desktop_mascots\.js/);
assert.match(mascots,/window\.__PORTAL_DESKTOP__!==true/);
assert.match(mascots,/prefers-reduced-motion: reduce/);
assert.match(mascots,/pointer-events:none/);
for(const key of ['hello','happy','wow','cheer','sad','sleep','shrug','ok']) assert.match(mascots,new RegExp('\\"'+key+'\\"'));
assert.match(mascots,/stickers\/catalog\.json/);
assert.match(mascots,/x\.enabled===true/);
assert.match(mascots,/SAFE\.test\(x\.asset\)/);
assert.match(mascots,/!x\.asset\.includes\(\"\/\"\)/);
assert.match(code,/ProcessFailed[\s\S]+_webRecoveryPending[\s\S]+Browser\.Reload\(\)/);
assert.match(app,/window\.portalBack=/);
assert.match(app,/S\.history\.push\(S\.page\)/);
assert.match(app,/window\.portalHome=/);
assert.match(app,/autoCheckUpdates\(\)/);
assert.match(app,/HTTP разрешён только для локального сервера/);
assert.match(app,/url\.protocol!=='https:'&&!\(url\.protocol==='http:'&&loopback\)/);
assert.match(xaml,/Content="Обновить PORTAL"[^>]+Click="CheckUpdate_Click"/);
assert.match(code,/private const int CurrentBuild = 58/);
assert.match(code,/WebViewSoftwareRenderingArguments = "--disable-gpu --disable-gpu-compositing"/);
assert.match(code,/AdditionalBrowserArguments = WebViewArguments\(\)/);
assert.match(code,/PORTAL_WEBVIEW_SOFTWARE_RENDERING/);
assert.match(code,/catch \(HttpRequestException\)[\s\S]+LoadGithubUpdateManifestAsync\(\)/);
assert.match(code,/catch \(TaskCanceledException\)[\s\S]+LoadGithubUpdateManifestAsync\(\)/);
assert.match(code,/if \(_serverOrigin is not null\)[\s\S]+githubManifest = await LoadGithubUpdateManifestAsync\(\)/);
assert.doesNotMatch(code,/Сначала подключитесь к серверу PORTAL/);
assert.match(code,/PORTAL-Desktop\/5\.8\.0/);
assert.match(code,/DownloadAndInstallUpdate\(manifest, downloadUri\)/);
assert.match(code,/ServerDiscoveryUrl = "https:\/\/raw\.githubusercontent\.com\/portal26ernest-arch\/-Portal-zrp\/main\/portal-server\.json"/);
assert.match(code,/RefreshOfficialServerAsync\(\)/);
assert.match(code,/ProbeOfficialServerAsync\(next\)/);
assert.match(code,/host\.Equals\("api\.vart-portal\.ru"[\s\S]+host\.Equals\("reserve-api\.vart-portal\.ru"/);
assert.doesNotMatch(code,/LegacyServerOrigin|endsWith\("\.trycloudflare\.com"\)|host\.EndsWith\("\.vart-portal\.ru"/);
const acceptsOfficialDiscoveryOrigin=value=>{try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&!u.search&&!u.hash&&(u.port===''||u.port==='443')&&(u.pathname===''||u.pathname==='/')&&['api.vart-portal.ru','reserve-api.vart-portal.ru'].includes(u.hostname.toLowerCase());}catch{return false;}};
for(const acceptedOrigin of ['https://api.vart-portal.ru','https://reserve-api.vart-portal.ru']) assert.equal(acceptsOfficialDiscoveryOrigin(acceptedOrigin),true,acceptedOrigin);
for(const rejectedOrigin of ['https://attacker.example','https://evil.api.vart-portal.ru','https://x.trycloudflare.com','https://2a03-6f00-a--1-f426.sslip.io','http://api.vart-portal.ru']) assert.equal(acceptsOfficialDiscoveryOrigin(rejectedOrigin),false,rejectedOrigin);
const desktopDiscovery=code.slice(code.indexOf('private async Task<ServerRefreshResult> RefreshOfficialServerAsync'),code.indexOf('private static Task<bool> ProbeOfficialServerAsync'));
assert.ok(desktopDiscovery.indexOf('TryNormalizeOfficialOrigin') < desktopDiscovery.indexOf('ProbeOfficialServerAsync(next)'), 'Desktop discovery must reject an origin before probing it');
assert.ok(desktopDiscovery.indexOf('TryNormalizeOfficialOrigin') < desktopDiscovery.indexOf('MigrateOutboxOrigin'), 'Desktop discovery must reject an origin before outbox migration');
assert.ok(desktopDiscovery.indexOf('TryNormalizeOfficialOrigin') < desktopDiscovery.indexOf('SaveOrigin(next)'), 'Desktop discovery must reject an origin before persisting it');
assert.ok(desktopDiscovery.indexOf('TryNormalizeOfficialOrigin') < desktopDiscovery.indexOf('ConnectAsync(next'), 'Desktop discovery must reject an origin before connecting WebView');
assert.doesNotMatch(desktopDiscovery,/Authorization|Bearer|AccessToken/,'Desktop discovery must not send auth while validating an advertised origin');
assert.match(code,/if \(!IsAutomaticPortalOrigin\(origin\)\)[\s\S]+_cacheBridge = null;[\s\S]+return;/);
assert.match(code,/AddHostObjectToScript\("portalDesktopCache", _cacheBridge\)/);
assert.match(code,/TrustedFallbackServerOrigin = "https:\/\/reserve-api\.vart-portal\.ru"/);
assert.match(code,/PrimaryServerOrigin = "https:\/\/api\.vart-portal\.ru"/);
assert.match(code,/uri\.Scheme\.Equals\(Uri\.UriSchemeHttps/);
assert.match(code,/uri\.IsLoopback/);
assert.match(code,/ConnectFirstAvailablePortalServerAsync/);
assert.match(code,/ProbePortalServerAsync/);
assert.match(code,/server-discovery-revision\.txt/);
assert.match(cache,/MigrateOutboxOrigin\(string settingsDir, string oldOrigin, string newOrigin\)/);
assert.match(cache,/MigrateOutboxOrigin\(string settingsDir, string oldOrigin, string newOrigin, Action<int>\? afterCopy\)/);
assert.ok(cache.indexOf('afterCopy?.Invoke(copied)') < cache.indexOf('// Complete the target copy'), 'Desktop injected failure must happen before source cleanup');
assert.match(code,/PropertyNamingPolicy = JsonNamingPolicy\.SnakeCaseLower/);
assert.match(code,/api\.github\.com\/repos\/\{GithubRepository\}\/releases\?per_page=50/);
assert.match(code,/portal-desktop-v\(\\d\+\)\\\.\(\\d\+\)\\\.0/);
assert.match(code,/AllowedUpdateRedirect\(initial, next\)/);
assert.match(code,/\.githubusercontent\.com/);
assert.match(code,/ZipFile\.OpenRead\(packagePath\)/);
assert.match(code,/SHA-256 пакета обновления не совпадает/);
assert.match(code,/DesktopUpdateSignature\.Verify\(manifest\)/);
assert.match(code,/portal-desktop-update\.json/);
assert.match(signature,/PORTAL-DESKTOP-UPDATE-V1/);
assert.match(signature,/RSASignaturePadding\.Pkcs1/);
assert.match(signature,/rsa\.VerifyData/);
assert.match(signature,/Portal\.Desktop\.desktop-update-signing-public\.pem/);
assert.match(fs.readFileSync(path.join(repo,'desktop_windows/Portal.Desktop.csproj'),'utf8'),/EmbeddedResource Include="desktop-update-signing-public\.pem"/);
assert.match(windowsWorkflow,/PORTAL_DESKTOP_UPDATE_SIGNING_PRIVATE_KEY/);
assert.match(windowsWorkflow,/openssl dgst -sha256 -sign/);
assert.match(windowsWorkflow,/portal-desktop-update\.json/);
assert.match(windowsWorkflow,/test -n "\$PORTAL_DESKTOP_UPDATE_SIGNING_PRIVATE_KEY"/);
assert.match(code,/githubManifest\.Build > serverManifest\.Build/);
assert.match(code,/portal-desktop-43-style/);
assert.match(code,/portalDesktop43Patched/);
assert.doesNotMatch(code,/ProbePortalWebAsync/);
assert.match(code,/options\.IsInPrivateModeEnabled = false/);
assert.match(code,/Settings\.IsPasswordAutosaveEnabled = true/);
assert.doesNotMatch(code,/Settings\.IsPasswordAutosaveEnabled = false/);
assert.match(xaml,/встроенный менеджер паролей WebView2/);
assert.match(code,/Browser\.Source = new Uri\(origin \+ "\/web\/"\)/);
assert.match(code,/_pendingPersistOrigin = persist \? origin : null/);
assert.match(code,/AddHostObjectToScript\("portalDesktopCache", _cacheBridge\)/);
assert.match(code,/_cacheBridge\?\.ClearAll\(\)/);
assert.match(code,/Profile\.ClearBrowsingDataAsync\(\)/);
assert.match(cache,/DataProtectionScope\.CurrentUser/);
assert.match(cache,/ProtectedData\.Protect/);
assert.match(cache,/ProtectedData\.Unprotect/);
assert.match(cache,/CompanyDirectory\(string companyId\)/);
assert.match(cache,/Delete\(string companyId, string cacheKey\)/);
assert.match(cache,/EnqueueMutation\(string companyId/);
assert.match(cache,/PendingMutations\(string companyId/);
assert.match(cache,/RemoveMutation\(string companyId/);
assert.match(cache,/company-outbox/);
assert.match(cache,/long\.TryParse\(companyId/);
assert.match(code,/\['Работа',[\s\S]+\['Управление',[\s\S]+\['Учёт и финансы',[\s\S]+\['Аналитика',[\s\S]+\['Система'/);
assert.match(code,/UpdateDesktopShortcuts\(executable, target, version\)/);
assert.match(code,/Process\.Start\(new ProcessStartInfo\(executable\)/);
assert.match(windowsWorkflow,/Require manual release from current reviewed main[\s\S]+GITHUB_REF -ne "refs\/heads\/main"[\s\S]+GITHUB_SHA -ne \$mainCommit/);
assert.ok(windowsWorkflow.indexOf('Require manual release from current reviewed main') <
  windowsWorkflow.indexOf('Publish self-contained Windows client'),
  'Desktop release provenance must be checked before a manually dispatched release build');
assert.ok(windowsWorkflow.indexOf('Create signed Desktop update manifest') <
  windowsWorkflow.indexOf('gh release create'),
  'Desktop release must sign update metadata before publishing it');
assert.match(windowsWorkflow,/Recheck reviewed main before signing and publishing[\s\S]+GITHUB_EVENT_NAME[\s\S]+refs\/heads\/main[\s\S]+GITHUB_SHA/);
assert.ok(windowsWorkflow.indexOf('Recheck reviewed main before signing and publishing') <
  windowsWorkflow.indexOf('Create signed Desktop update manifest'),
  'Desktop release must revalidate main provenance before the private key is exposed');
assert.match(windowsWorkflow,/Publish immutable Desktop release[\s\S]+Release tag already exists: \$TAG[\s\S]+gh release create/);
assert.doesNotMatch(windowsWorkflow,/tags: \["portal-desktop-v\*"\]/);
console.log('Desktop shell navigation, branding and self-update checks: OK');
