const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const repo=path.join(__dirname,'../..');
const xaml=fs.readFileSync(path.join(repo,'desktop_windows/MainWindow.xaml'),'utf8');
const code=fs.readFileSync(path.join(repo,'desktop_windows/MainWindow.xaml.cs'),'utf8');
const app=fs.readFileSync(path.join(repo,'android_src/app/src/main/assets/app.js'),'utf8');
const cache=fs.readFileSync(path.join(repo,'desktop_windows/DesktopCacheBridge.cs'),'utf8');
assert.match(xaml,/x:Name="HomeButton"[^>]+Click="Home_Click"/);
assert.match(xaml,/PreviewMouseWheel="Browser_PreviewMouseWheel"/);
assert.match(code,/ExecuteScriptAsync\("Boolean\(window\.portalBack && window\.portalBack\(\)\)"\)/);
assert.match(code,/ExecuteScriptAsync\("Boolean\(window\.portalHome && window\.portalHome\(\)\)"\)/);
assert.match(code,/window\.scrollBy\(\{\{top:/);
assert.match(code,/ProcessFailed[\s\S]+_webRecoveryPending[\s\S]+Browser\.Reload\(\)/);
assert.match(app,/window\.portalBack=/);
assert.match(app,/S\.history\.push\(S\.page\)/);
assert.match(app,/window\.portalHome=/);
assert.match(app,/autoCheckUpdates\(\)/);
assert.match(xaml,/Content="Обновить PORTAL"[^>]+Click="CheckUpdate_Click"/);
assert.match(code,/private const int CurrentBuild = 53/);
assert.match(code,/private const string CurrentVersion = "5\.3\.0"/);
assert.match(code,/WebViewCompatibilityArguments = "--disable-gpu --disable-gpu-compositing"/);
assert.match(code,/AdditionalBrowserArguments = WebViewCompatibilityArguments/);
assert.match(code,/catch \(HttpRequestException\)[\s\S]+LoadGithubUpdateManifestAsync\(\)/);
assert.match(code,/catch \(TaskCanceledException\)[\s\S]+LoadGithubUpdateManifestAsync\(\)/);
assert.match(code,/if \(_serverOrigin is not null\)[\s\S]+githubManifest = await LoadGithubUpdateManifestAsync\(\)/);
assert.doesNotMatch(code,/Сначала подключитесь к серверу PORTAL/);
assert.match(code,/PORTAL-Desktop\/5\.3\.0/);
assert.match(code,/DownloadAndInstallUpdate\(manifest, downloadUri\)/);
assert.match(code,/_ = CheckForUpdateAsync\(interactive: false\)/);
assert.match(code,/if \(_updateCheckInProgress \|\| \(!interactive && _startupUpdateChecked\)\) return/);
assert.match(code,/if \(!interactive\) _startupUpdateChecked = true/);
assert.match(code,/if \(interactive\) MessageBox\.Show\("Установлена актуальная версия PORTAL Desktop\./);
assert.match(code,/PropertyNamingPolicy = JsonNamingPolicy\.SnakeCaseLower/);
assert.match(code,/api\.github\.com\/repos\/\{GithubRepository\}\/releases\?per_page=50/);
assert.match(code,/portal-desktop-v\(\\d\+\)\\\.\(\\d\+\)\\\.0/);
assert.match(code,/AllowedUpdateRedirect\(initial, next\)/);
assert.match(code,/\.githubusercontent\.com/);
assert.match(code,/ZipFile\.OpenRead\(packagePath\)/);
assert.match(code,/SHA-256 пакета обновления не совпадает/);
assert.match(code,/githubManifest\.Build > serverManifest\.Build/);
assert.match(code,/portal-desktop-43-style/);
assert.match(code,/portalDesktop43Patched/);
assert.doesNotMatch(code,/ProbePortalWebAsync/);
assert.match(code,/options\.IsInPrivateModeEnabled = false/);
assert.match(code,/Browser\.Source = new Uri\(origin \+ "\/web\/"\)/);
assert.match(code,/_pendingPersistOrigin = persist \? origin : null/);
assert.match(code,/AddHostObjectToScript\("portalDesktopCache", _cacheBridge\)/);
assert.match(code,/_cacheBridge\?\.ClearAll\(\)/);
assert.match(cache,/DataProtectionScope\.CurrentUser/);
assert.match(cache,/ProtectedData\.Protect/);
assert.match(cache,/ProtectedData\.Unprotect/);
assert.match(cache,/CompanyDirectory\(string companyId\)/);
assert.match(cache,/long\.TryParse\(companyId/);
assert.match(cache,/public string GetAppMetadata\(\)/);
assert.match(cache,/FileVersionInfo\.GetVersionInfo\(executable\)/);
assert.match(cache,/PortalBuildDate/);
assert.match(cache,/channel = "release"/);
assert.match(code,/await ApplyDesktopMetadataAsync\(\)/);
assert.match(code,/private async Task ApplyDesktopMetadataAsync\(\)/);
assert.match(code,/AddScriptToExecuteOnDocumentCreatedAsync\(bootstrapScript\)/);
assert.match(code,/ConfigureDesktopCacheAsync\(string origin\)/);
assert.match(code,/_metadataBootstrapRegistered/);
assert.doesNotMatch(code,/new MutationObserver\(/);
assert.match(code,/window\.__PORTAL_DESKTOP_METADATA__ = parsed/);
assert.match(code,/window\.PortalNative\.getAppMetadata = \(\) => raw/);
assert.match(code,/S\.metadata = parsed/);
assert.match(code,/__portalDesktopAboutPatched/);
assert.match(code,/StatusText\.Text = \$"Подключено · \{CurrentVersion\} · build \{CurrentBuild\}"/);
assert.match(code,/AddScriptToExecuteOnDocumentCreatedAsync\(bootstrapScript\)/);
assert.match(code,/\['Работа',[\s\S]+\['Управление',[\s\S]+\['Учёт и финансы',[\s\S]+\['Аналитика',[\s\S]+\['Система'/);
assert.match(code,/UpdateDesktopShortcuts\(executable, target, version\)/);
assert.match(code,/Process\.Start\(new ProcessStartInfo\(executable\)/);
console.log('Desktop shell navigation, branding and self-update checks: OK');
