const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');

const main=fs.readFileSync(path.join(__dirname,'../app/src/main/java/ru/portal/app/MainActivity.java'),'utf8');
assert.match(main,/SYSTEM_UI_FLAG_IMMERSIVE_STICKY/);
assert.match(main,/SYSTEM_UI_FLAG_HIDE_NAVIGATION/);
assert.match(main,/SYSTEM_UI_FLAG_FULLSCREEN/);
assert.match(main,/onWindowFocusChanged/);
assert.match(main,/saveBase64FileAsync/);
assert.match(main,/onShowFileChooser/);
assert.match(main,/FileChooserParams\.parseResult/);
assert.match(main,/filePathCallback\.onReceiveValue\(result\)/);
assert.match(main,/filePathCallback\.onReceiveValue\(null\)/);
assert.match(main,/startsWith\(\"file:\/\/\/android_asset\/\"\)/);
assert.match(main,/seller\.ozon\.ru/);
assert.match(main,/seller\.wildberries\.ru/);
assert.match(main,/uri\.getPort\(\)!=-1 && uri\.getPort\(\)!=443/);
assert.match(main,/Intent\.ACTION_VIEW/);
assert.match(main,/image\/jpeg/);
assert.match(main,/chat-file.*4 \* 1024 \* 1024/);
assert.match(main,/MediaStore\.Downloads\.EXTERNAL_CONTENT_URI/);
assert.match(main,/Downloads.*PORTAL|DIRECTORY_DOWNLOADS \+ "\/PORTAL"/);
assert.match(main,/20 \* 1024 \* 1024/);
assert.match(main,/document-file.*30 \* 1024 \* 1024/);
assert.match(main,/openxmlformats-officedocument\.spreadsheetml\.sheet/);
assert.match(main,/"application\/json"\.equals\(mimeType\)/);
assert.match(main,/shareBase64FileAsync/);
assert.match(main,/Intent\.ACTION_SEND/);
assert.match(main,/Intent\.createChooser\(send/);
assert.match(main,/Intent\.EXTRA_EMAIL/);
assert.match(main,/Intent\.EXTRA_SUBJECT/);
assert.match(main,/Intent\.EXTRA_TEXT/);
assert.match(main,/FileProvider\.getUriForFile/);
assert.match(main,/FLAG_GRANT_READ_URI_PERMISSION/);
assert.doesNotMatch(main,/Uri\.fromFile/);
assert.doesNotMatch(main,/api\.telegram\.org|BOT_TOKEN|OWNER_TELEGRAM_ID/);
assert.doesNotMatch(main,/Uri\.fromFile|"file:\/\/"/);
const manifest=fs.readFileSync(path.join(__dirname,'../app/src/main/AndroidManifest.xml'),'utf8');
assert.match(manifest,/androidx\.core\.content\.FileProvider/);
assert.match(manifest,/android:exported="false"/);
assert.match(manifest,/android:grantUriPermissions="true"/);
const providerPaths=fs.readFileSync(path.join(__dirname,'../app/src/main/res/xml/share_paths.xml'),'utf8');
assert.match(providerPaths,/<cache-path[^>]+path="shared\/"/);
console.log('Native shell checks: OK');
