const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');

const main=fs.readFileSync(path.join(__dirname,'../app/src/main/java/ru/portal/app/MainActivity.java'),'utf8');
const localCache=fs.readFileSync(path.join(__dirname,'../app/src/main/java/ru/portal/app/PortalLocalCache.java'),'utf8');
assert.match(main,/SYSTEM_UI_FLAG_IMMERSIVE_STICKY/);
assert.match(main,/SYSTEM_UI_FLAG_HIDE_NAVIGATION/);
assert.match(main,/SYSTEM_UI_FLAG_FULLSCREEN/);
assert.match(main,/onWindowFocusChanged/);
assert.match(main,/saveBase64FileAsync/);
assert.match(main,/onShowFileChooser/);
assert.match(main,/FileChooserParams\.parseResult/);
assert.match(main,/filePathCallback\.onReceiveValue\(result\)/);
assert.match(main,/filePathCallback\.onReceiveValue\(null\)/);
assert.match(main,/startsWith\(\"file:\/\/\/android_asset\/\"\)/);
assert.match(main,/seller\.ozon\.ru/);
assert.match(main,/seller\.wildberries\.ru/);
assert.match(main,/uri\.getPort\(\)!=-1 && uri\.getPort\(\)!=443/);
assert.match(main,/Intent\.ACTION_VIEW/);
assert.match(main,/image\/jpeg/);
assert.match(main,/chat-file.*4 \* 1024 \* 1024/);
assert.match(main,/MediaStore\.Downloads\.EXTERNAL_CONTENT_URI/);
assert.match(main,/Downloads.*PORTAL|DIRECTORY_DOWNLOADS \+ "\/PORTAL"/);
assert.match(main,/20 \* 1024 \* 1024/);
assert.match(main,/document-file.*30 \* 1024 \* 1024/);
assert.match(main,/openxmlformats-officedocument\.spreadsheetml\.sheet/);
assert.match(main,/"application\/json"\.equals\(mimeType\)/);
assert.match(main,/shareBase64FileAsync/);
assert.match(main,/Intent\.ACTION_SEND/);
assert.match(main,/Intent\.createChooser\(send/);
assert.match(main,/Intent\.EXTRA_EMAIL/);
assert.match(main,/Intent\.EXTRA_SUBJECT/);
assert.match(main,/Intent\.EXTRA_TEXT/);
assert.match(main,/FileProvider\.getUriForFile/);
assert.match(main,/FLAG_GRANT_READ_URI_PERMISSION/);
assert.match(main,/downloadAndInstallUpdate/);
assert.match(main,/m\.getInt\("schemaVersion"\) != 1/);
assert.match(main,/Instant\.parse\(publishedAt\)/);
assert.match(main,/100L? \* 1024 \* 1024/);
assert.match(main,/downloadOfficialToFile/);
assert.match(main,/digest\.update\(buf, 0, n\)/);
assert.doesNotMatch(main,/getOfficial\(url, 100 \* 1024 \* 1024, false\)/);
assert.match(main,/MessageDigest\.isEqual\(expected, response\.sha256\)/);
assert.match(main,/BuildConfig\.APPLICATION_ID\.equals\(archive\.packageName\)/);
assert.match(main,/archived<=BuildConfig\.VERSION_CODE \|\| archived!=expectedVersion/);
assert.match(main,/GET_SIGNING_CERTIFICATES/);
assert.match(main,/GET_SIGNATURES/);
assert.match(main,/MessageDigest\.isEqual\(certDigest\(installed,a\[0\]\),certDigest\(archive,b\[0\]\)\)/);
assert.match(main,/ACTION_MANAGE_UNKNOWN_APP_SOURCES/);
assert.match(main,/context\.getPackageManager\(\)\.canRequestPackageInstalls\(\)/);
assert.match(main,/context\.startActivity\(settings\)/);
assert.match(main,/context\.startActivity\(install\)/);
assert.match(main,/signingInfo==null/);
assert.match(main,/application\/vnd\.android\.package-archive/);
assert.match(main,/MAX|redirects <= 5/);
assert.match(main,/validManifestUrl/);
assert.match(main,/portal26ernest-arch\/-Portal-zrp/);
assert.match(main,/release-assets\.githubusercontent\.com/);
assert.match(main,/isLegacyLocalServer/);
assert.match(main,/SERVER_DISCOVERY_URL/);
assert.match(main,/raw\.githubusercontent\.com/);
assert.match(main,/checkUpdatesAndServer/);
assert.match(main,/probeOfficialServer/);
assert.match(main,/server_discovery_revision/);
assert.match(main,/migrateOutboxOrigin/);
const discoveryNormalize=main.slice(main.indexOf('private String normalizeOfficialApiUrl'),main.indexOf('private boolean isSafeServerTransport'));
assert.match(discoveryNormalize,/"api\.vart-portal\.ru"\.equals\(host\) \|\| "reserve-api\.vart-portal\.ru"\.equals\(host\)/);
assert.doesNotMatch(discoveryNormalize,/endsWith\("\.trycloudflare\.com"\)|host\.endsWith\("\.vart-portal\.ru"\)/);
const acceptsOfficialDiscoveryOrigin=value=>{try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&!u.search&&!u.hash&&(u.port===''||u.port==='443')&&(u.pathname===''||u.pathname==='/')&&['api.vart-portal.ru','reserve-api.vart-portal.ru'].includes(u.hostname.toLowerCase());}catch{return false;}};
for(const acceptedOrigin of ['https://api.vart-portal.ru','https://reserve-api.vart-portal.ru']) assert.equal(acceptsOfficialDiscoveryOrigin(acceptedOrigin),true,acceptedOrigin);
for(const rejectedOrigin of ['https://attacker.example','https://evil.api.vart-portal.ru','https://x.trycloudflare.com','https://2a03-6f00-a--1-f426.sslip.io','http://api.vart-portal.ru']) assert.equal(acceptsOfficialDiscoveryOrigin(rejectedOrigin),false,rejectedOrigin);
const discovery=main.slice(main.indexOf('private JSONObject refreshOfficialServer'),main.indexOf('private boolean validDiscoveryUrl'));
assert.ok(discovery.indexOf('normalizeOfficialApiUrl') < discovery.indexOf('probeOfficialServer(next)'), 'Android discovery must reject an origin before probing it');
assert.ok(discovery.indexOf('normalizeOfficialApiUrl') < discovery.indexOf('migrateOutboxOrigin'), 'Android discovery must reject an origin before outbox migration');
assert.ok(discovery.indexOf('normalizeOfficialApiUrl') < discovery.indexOf('putString("server_url", next)'), 'Android discovery must reject an origin before persisting it');
assert.doesNotMatch(discovery,/Authorization|Bearer|requestAsync/,'Android discovery must not send auth while validating an advertised origin');
assert.match(localCache,/migrateOutboxOrigin\(String oldOrigin, String newOrigin, int failAfterCopies\)/);
assert.ok(localCache.indexOf('failAfterCopies >= 0') < localCache.indexOf('// The new origin is complete'), 'Android migration fault injection must stop before source cleanup');
assert.ok(localCache.indexOf('for (File company : companies) {\n                File[] rows') > localCache.indexOf('// The new origin is complete'), 'Android migration must defer source cleanup until all target copies finish');
assert.match(main,/TRUSTED_FALLBACK_API_URL = "https:\/\/reserve-api\.vart-portal\.ru"/);
assert.match(main,/resolveServerForRequest\(getServerUrl\(\)\)/);
assert.match(main,/probeOfficialServer\(TRUSTED_FALLBACK_API_URL\)/);
assert.match(main,/private boolean isSafeServerTransport\(URL url\)/);
assert.match(main,/isSafeServerTransport\(url\)\) throw new Exception\("Небезопасный адрес сервера"\)/);
assert.match(main,/if \(isSafeServerTransport\(url\) && url\.getUserInfo\(\) == null/);
assert.ok(main.includes('host.matches("127(?:\\\\.[0-9]{1,3}){3}")'));
assert.match(main,/SERVER_HEALTH_TTL_MS/);
assert.match(main,/migrateAutomaticServerAfterUpgrade/);
assert.match(main,/server_config_version_code/);
assert.match(main,/BuildConfig\.VERSION_CODE/);
assert.match(localCache,/migrateOutboxOrigin\(String oldOrigin, String newOrigin\)/);
assert.match(main,/127\.0\.0\.1/);
assert.match(main,/portal\.invalid/);
assert.match(main,/prefs\.edit\(\)\.remove\("server_url"\)\.apply\(\)/);
assert.doesNotMatch(main,/github-releases\.githubusercontent\.com|s3\.amazonaws\.com/);
assert.doesNotMatch(main,/Uri\.fromFile/);
assert.doesNotMatch(main,/api\.telegram\.org|BOT_TOKEN|OWNER_TELEGRAM_ID/);
assert.doesNotMatch(main,/Uri\.fromFile|"file:\/\/"/);
assert.match(main,/CACHE_MAX_AGE_MS = 30L \* 24 \* 60 \* 60 \* 1000/);
assert.match(main,/setCacheCompany/);
assert.match(main,/queueMutation/);
for(const safePath of ['/api/v3/work','/api/v3/links','/api/v3/batches','/api/v3/tasks','/api/v3/shipments','/api/v3/returns']) assert.ok(main.includes(`"${safePath}"`),safePath);
const queuePolicy=main.slice(main.indexOf('private boolean queueableMutationPath'),main.indexOf('@JavascriptInterface\n        public boolean queueMutation'));
for(const deniedPath of ['/api/v3/timers','/api/v3/payments','/api/v3/invoices','/api/v3/permissions','/api/v3/settings','/api/v3/tariffs']) assert.ok(!queuePolicy.includes(deniedPath),deniedPath);
assert.match(main,/pendingMutations/);
assert.match(main,/removeMutation/);
assert.match(localCache,/AndroidKeyStore/);
assert.match(localCache,/AES\/GCM\/NoPadding/);
assert.match(localCache,/company-cache/);
assert.match(localCache,/boolean delete\(String serverOrigin/);
assert.match(main,/invalidateCacheForMutation/);
assert.match(localCache,/company-outbox/);
assert.match(localCache,/MAX_OUTBOX_ITEMS = 1000/);
const manifest=fs.readFileSync(path.join(__dirname,'../app/src/main/AndroidManifest.xml'),'utf8');
assert.match(manifest,/androidx\.core\.content\.FileProvider/);
assert.match(manifest,/android\.permission\.REQUEST_INSTALL_PACKAGES/);
assert.match(manifest,/android:exported="false"/);
assert.match(manifest,/android:grantUriPermissions="true"/);
const providerPaths=fs.readFileSync(path.join(__dirname,'../app/src/main/res/xml/share_paths.xml'),'utf8');
assert.match(providerPaths,/<cache-path[^>]+path="shared\/"/);
assert.match(providerPaths,/<cache-path[^>]+path="updates\/"/);
assert.doesNotMatch(providerPaths,/<cache-path[^>]+path="\."/);
console.log('Native shell checks: OK');
