const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');

const main=fs.readFileSync(path.join(__dirname,'../app/src/main/java/ru/portal/app/MainActivity.java'),'utf8');
assert.match(main,/SYSTEM_UI_FLAG_IMMERSIVE_STICKY/);
assert.match(main,/SYSTEM_UI_FLAG_HIDE_NAVIGATION/);
assert.match(main,/SYSTEM_UI_FLAG_FULLSCREEN/);
assert.match(main,/onWindowFocusChanged/);
assert.match(main,/saveBase64FileAsync/);
assert.match(main,/onShowFileChooser/);
assert.match(main,/FileChooserParams\.parseResult/);
assert.match(main,/image\/jpeg/);
assert.match(main,/chat-file.*4 \* 1024 \* 1024/);
assert.match(main,/MediaStore\.Downloads\.EXTERNAL_CONTENT_URI/);
assert.match(main,/Downloads.*PORTAL|DIRECTORY_DOWNLOADS \+ "\/PORTAL"/);
assert.match(main,/20 \* 1024 \* 1024/);
assert.match(main,/document-file.*30 \* 1024 \* 1024/);
assert.match(main,/openxmlformats-officedocument\.spreadsheetml\.sheet/);
assert.match(main,/"application\/json"\.equals\(mimeType\)/);
assert.doesNotMatch(main,/api\.telegram\.org|BOT_TOKEN|OWNER_TELEGRAM_ID/);
console.log('Native shell checks: OK');
