"""Static guard checks only; real PostgreSQL execution belongs to integration tests."""
import re
import unittest
from pathlib import Path


SQL = (Path(__file__).parent / 'migrations' / 'postgresql_runtime.sql').read_text(encoding='utf-8')


class PostgreSQLRuntimeSchemaContract(unittest.TestCase):
    def test_migration_is_additive_and_transactional(self):
        statements = re.sub(r'--[^\n]*', '', SQL).strip()
        self.assertTrue(statements.startswith('BEGIN;'))
        self.assertTrue(statements.endswith('COMMIT;'))
        self.assertNotRegex(statements, r'(?i)\b(DROP|TRUNCATE|DISABLE)\b')
        self.assertNotRegex(statements, r'(?i)\b(?:UPDATE|DELETE\s+FROM)\s+(?:work_log|portal_production|companies)\b')
        self.assertIn('ON CONFLICT(version) DO NOTHING', SQL)

    def test_tenant_defaults_fail_closed(self):
        self.assertIn("NULLIF(current_setting(''portal.company_id'',true),'''')::bigint", SQL)
        for table in ('app_users', 'app_sessions', 'employees', 'portal_clients',
                      'portal_client_operations', 'portal_production',
                      'portal_production_migrations', 'work_log', 'payroll_payments',
                      'payroll_transactions', 'client_invoices', 'client_payments',
                      'materials', 'material_movements', 'production_jobs'):
            self.assertIn("'" + table + "'", SQL)
        self.assertIn('ALTER COLUMN company_id SET DEFAULT', SQL)

    def test_material_projection_has_tenant_relationships_and_rls(self):
        self.assertIn('ADD COLUMN IF NOT EXISTS min_stock', SQL)
        self.assertIn('ADD COLUMN IF NOT EXISTS updated_at', SQL)
        self.assertIn('PRIMARY KEY(company_id,work_id,material_id)', SQL)
        self.assertIn('FOREIGN KEY(company_id,work_id) REFERENCES work_log(company_id,id)', SQL)
        self.assertIn('FOREIGN KEY(company_id,material_id) REFERENCES materials(company_id,id)', SQL)
        self.assertIn('ALTER TABLE work_material_consumption FORCE ROW LEVEL SECURITY', SQL)
        self.assertIn('WITH CHECK (company_id =', SQL)
        self.assertIn('BEFORE DELETE ON work_material_consumption', SQL)

    def test_control_plane_and_batch_history_protection(self):
        self.assertIn('BEFORE UPDATE ON platform_audit', SQL)
        self.assertIn("attname='id' AND attidentity=''", SQL)
        self.assertIn('ADD GENERATED BY DEFAULT AS IDENTITY', SQL)
        self.assertIn('FOREIGN KEY(user_id) REFERENCES platform_owners(id)', SQL)
        self.assertIn('FOREIGN KEY(actor_id) REFERENCES platform_owners(id)', SQL)
        self.assertIn('batch number is immutable', SQL)
        self.assertIn('IS DISTINCT FROM', SQL)

    def test_ledger_checks_reject_missing_json_fields(self):
        self.assertIn("(payload::jsonb ->> 'company_id') IS NOT NULL", SQL)
        self.assertIn("(payload::jsonb ->> 'id') IS NOT NULL", SQL)
        self.assertIn("NULLIF(btrim(payload::jsonb ->> 'number'),'') IS NOT NULL", SQL)
        self.assertIn("jsonb_typeof(payload::jsonb -> 'company_id') = 'number'", SQL)
        self.assertIn("jsonb_typeof(payload::jsonb -> 'id') = 'string'", SQL)


if __name__ == '__main__':
    unittest.main()
