"""Static PostgreSQL contract for the payroll settlement migration."""
import re
import unittest
from pathlib import Path


SQL=(Path(__file__).parent/'migrations'/'postgresql_stage6_payroll_settlement.sql').read_text(encoding='utf-8')


class PostgreSQLPayrollSettlementSchemaContract(unittest.TestCase):
    def test_migration_is_additive_repeatable_and_transactional(self):
        statements=re.sub(r'--[^\n]*','',SQL).strip()
        self.assertTrue(statements.startswith('BEGIN;'))
        self.assertTrue(statements.endswith('COMMIT;'))
        self.assertIn('CREATE TABLE IF NOT EXISTS payroll_settlement_entries',SQL)
        self.assertIn('CREATE INDEX IF NOT EXISTS payroll_settlement_period_employee',SQL)
        self.assertIn('ON CONFLICT(company_id,version) DO NOTHING',SQL)
        self.assertNotRegex(statements,r'(?i)\b(?:DROP\s+TABLE|TRUNCATE|DELETE\s+FROM|UPDATE\s+payroll_)\b')

    def test_exact_money_identity_and_idempotency_contract(self):
        self.assertIn('amount_minor BIGINT NOT NULL',SQL)
        self.assertNotRegex(SQL,r'amount_minor\s+(?:REAL|FLOAT|DOUBLE)')
        self.assertIn('employee_id BIGINT NOT NULL',SQL)
        self.assertNotIn('telegram_id BIGINT NOT NULL,\n payroll_period_id',SQL)
        self.assertIn('UNIQUE(company_id,request_id)',SQL)
        self.assertIn('FOREIGN KEY(company_id,employee_id) REFERENCES payroll_employee_identities(company_id,employee_id)',SQL)
        self.assertIn('FOREIGN KEY(company_id,legacy_employee_id) REFERENCES employees(company_id,telegram_id)',SQL)
        self.assertIn('employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY',SQL)

    def test_forced_rls_and_append_only_contract(self):
        self.assertIn('ALTER TABLE payroll_settlement_entries ENABLE ROW LEVEL SECURITY',SQL)
        self.assertIn('ALTER TABLE payroll_settlement_entries FORCE ROW LEVEL SECURITY',SQL)
        self.assertIn('USING (company_id=portal_current_company())',SQL)
        self.assertIn('WITH CHECK (company_id=portal_current_company())',SQL)
        self.assertIn('BEFORE UPDATE OR DELETE ON payroll_settlement_entries',SQL)
        self.assertIn("entry_type IN ('payout','adjustment','reversal')",SQL)

    def test_new_companies_receive_version_six(self):
        provision=re.search(r'CREATE OR REPLACE FUNCTION portal_provision_company.*?END;\n\$\$;',SQL,re.S)
        self.assertIsNotNone(provision)
        self.assertIn('(cid,6,CURRENT_TIMESTAMP::text)',provision.group(0))

    def test_canonical_mapping_and_closed_period_are_scoped_foreign_keys(self):
        self.assertIn('UNIQUE(company_id,legacy_employee_id)',SQL)
        self.assertIn('FOREIGN KEY(company_id,payroll_period_kind,payroll_period_id) REFERENCES portal_production(company_id,kind,id)',SQL)
        self.assertIn("payroll_period_kind='payroll_periods'",SQL)
        for table in ('payroll_employee_identities','payroll_settlement_entries'):
            self.assertIn('ALTER TABLE '+table+' ENABLE ROW LEVEL SECURITY',SQL)
            self.assertIn('ALTER TABLE '+table+' FORCE ROW LEVEL SECURITY',SQL)
        self.assertIn("ARRAY['payroll_employee_identities','payroll_settlement_entries']",SQL)

    def test_database_validation_serializes_balance_and_compensates_exactly_once(self):
        self.assertIn('pg_advisory_xact_lock(NEW.company_id)',SQL)
        self.assertIn("snapshot->>'status' IS DISTINCT FROM 'closed'",SQL)
        self.assertIn('e.company_id=NEW.company_id',SQL)
        self.assertIn('e.amount_minor=-NEW.amount_minor',SQL)
        self.assertIn('e.payroll_period_id=NEW.payroll_period_id',SQL)
        self.assertIn('WHERE reversal_of IS NOT NULL',SQL)
        self.assertIn('CREATE UNIQUE INDEX IF NOT EXISTS payroll_settlement_one_reversal',SQL)
        self.assertIn('IF NEW.amount_minor>balance THEN',SQL)
        self.assertIn('BEFORE INSERT ON payroll_settlement_entries',SQL)

    def test_actor_metadata_safe_function_scope_and_no_history_recalculation(self):
        self.assertIn("actor_kind IN ('user','platform_owner')",SQL)
        for field in ('occurred_at','reason','reference','request_id'):
            self.assertRegex(SQL,r'\b'+field+r' TEXT')
        function=re.search(r'CREATE OR REPLACE FUNCTION portal_payroll_settlement_validate.*?END;\n\$\$;',SQL,re.S).group(0)
        self.assertNotIn('SECURITY DEFINER',function)
        self.assertIn('SET search_path=pg_catalog,public',function)
        self.assertNotRegex(SQL,r'(?i)\bUPDATE\s+(?:portal_production|work_log|payroll_payments|payroll_transactions)\b')


if __name__=='__main__':unittest.main()
