-- Candidate PostgreSQL core schema for an isolated PORTAL database.
-- Review against a read-only inventory of the real SQLite copy before use.
-- Migration role applies it; application role must not own tables or BYPASSRLS.
BEGIN;

CREATE TABLE IF NOT EXISTS companies (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'active', monthly_price BIGINT NOT NULL DEFAULT 0,
 demo_enabled INTEGER NOT NULL DEFAULT 0, demo_start TEXT, demo_end TEXT,
 user_limit INTEGER DEFAULT 15, service_status TEXT NOT NULL DEFAULT 'active',
 created_at TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS platform_owners (
 id BIGINT PRIMARY KEY, company_id BIGINT NOT NULL DEFAULT 1 CHECK(company_id=1),
 username TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, pin_salt TEXT NOT NULL,
 pin_hash TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS platform_sessions (
 token_hash TEXT PRIMARY KEY, company_id BIGINT NOT NULL DEFAULT 1 CHECK(company_id=1),
 user_id BIGINT NOT NULL, expires_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS platform_audit (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 company_id BIGINT NOT NULL REFERENCES companies(id), actor_id BIGINT, event TEXT NOT NULL,
 outcome TEXT NOT NULL, details TEXT NOT NULL, created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS employees (
 telegram_id BIGINT NOT NULL, full_name TEXT, username TEXT, company_id BIGINT NOT NULL,
 PRIMARY KEY(company_id,telegram_id)
);
CREATE TABLE IF NOT EXISTS app_users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, company_id BIGINT NOT NULL, username TEXT NOT NULL,
 display_name TEXT NOT NULL, pin_salt TEXT NOT NULL, pin_hash TEXT NOT NULL,
 role TEXT NOT NULL, telegram_id BIGINT, active INTEGER NOT NULL DEFAULT 1,
 created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 PRIMARY KEY(company_id,id), UNIQUE(company_id,username)
);
CREATE TABLE IF NOT EXISTS app_sessions (
 token TEXT PRIMARY KEY, user_id BIGINT NOT NULL, company_id BIGINT NOT NULL,
 created_at TEXT NOT NULL, expires_at TEXT NOT NULL, portal_activity_id TEXT,
 FOREIGN KEY(company_id,user_id) REFERENCES app_users(company_id,id)
);
CREATE TABLE IF NOT EXISTS portal_clients (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, company_id BIGINT NOT NULL, name TEXT NOT NULL,
 active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 PRIMARY KEY(company_id,id), UNIQUE(company_id,name)
);
CREATE TABLE IF NOT EXISTS portal_client_operations (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, company_id BIGINT NOT NULL, client_id BIGINT NOT NULL,
 name TEXT NOT NULL, employee_rate NUMERIC, client_rate NUMERIC,
 active INTEGER NOT NULL DEFAULT 1, sort_order INTEGER NOT NULL DEFAULT 0,
 created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 PRIMARY KEY(company_id,id), UNIQUE(company_id,client_id,name),
 FOREIGN KEY(company_id,client_id) REFERENCES portal_clients(company_id,id)
);
CREATE TABLE IF NOT EXISTS manager_client_assignments (
 telegram_id BIGINT NOT NULL, client_id BIGINT NOT NULL,
 active INTEGER NOT NULL DEFAULT 1, company_id BIGINT NOT NULL,
 FOREIGN KEY(company_id,client_id) REFERENCES portal_clients(company_id,id)
);
CREATE TABLE IF NOT EXISTS work_log (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, company_id BIGINT NOT NULL, telegram_id BIGINT,
 username TEXT, first_name TEXT, client TEXT, operation TEXT,
 quantity NUMERIC, rate NUMERIC, salary NUMERIC, client_rate NUMERIC,
 revenue NUMERIC, direct_cost NUMERIC, created_at TEXT, updated_at TEXT,
 PRIMARY KEY(company_id,id)
);
CREATE TABLE IF NOT EXISTS payroll_payments (
 company_id BIGINT NOT NULL, telegram_id BIGINT, period_start TEXT,
 period_end TEXT, status TEXT
);
CREATE TABLE IF NOT EXISTS payroll_transactions (
 company_id BIGINT NOT NULL, telegram_id BIGINT, period_start TEXT,
 period_end TEXT, amount NUMERIC
);
CREATE TABLE IF NOT EXISTS client_invoices (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, company_id BIGINT NOT NULL, client TEXT, description TEXT,
 amount_due NUMERIC, due_date TEXT, created_at TEXT, closed_at TEXT,
 PRIMARY KEY(company_id,id)
);
CREATE TABLE IF NOT EXISTS client_payments (
 company_id BIGINT NOT NULL, invoice_id BIGINT, amount NUMERIC,
 FOREIGN KEY(company_id,invoice_id) REFERENCES client_invoices(company_id,id)
);
CREATE TABLE IF NOT EXISTS materials (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, company_id BIGINT NOT NULL, name TEXT NOT NULL,
 unit TEXT, unit_cost NUMERIC, stock_qty NUMERIC, active INTEGER NOT NULL DEFAULT 1,
 PRIMARY KEY(company_id,id)
);
CREATE TABLE IF NOT EXISTS material_movements (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, company_id BIGINT NOT NULL, material_id BIGINT NOT NULL,
 qty_change NUMERIC, unit_cost NUMERIC, movement_type TEXT, reference_type TEXT,
 reference_id TEXT, note TEXT, created_at TEXT, created_by BIGINT,
 PRIMARY KEY(company_id,id),
 FOREIGN KEY(company_id,material_id) REFERENCES materials(company_id,id)
);
CREATE TABLE IF NOT EXISTS operation_material_norms (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, company_id BIGINT NOT NULL, operation_id BIGINT NOT NULL,
 material_id BIGINT NOT NULL, qty_per_unit NUMERIC, active INTEGER NOT NULL DEFAULT 1,
 PRIMARY KEY(company_id,id),
 FOREIGN KEY(company_id,operation_id) REFERENCES portal_client_operations(company_id,id),
 FOREIGN KEY(company_id,material_id) REFERENCES materials(company_id,id)
);
CREATE TABLE IF NOT EXISTS production_jobs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, company_id BIGINT NOT NULL, client TEXT, operation TEXT,
 product_name TEXT, status TEXT, target_quantity NUMERIC, priority INTEGER,
 due_at TEXT, updated_at TEXT, completed_at TEXT, internal_cost NUMERIC,
 PRIMARY KEY(company_id,id)
);
CREATE TABLE IF NOT EXISTS production_job_progress (
 company_id BIGINT NOT NULL, job_id BIGINT NOT NULL, work_id BIGINT NOT NULL,
 telegram_id BIGINT, quantity NUMERIC, created_at TEXT,
 PRIMARY KEY(company_id,job_id,work_id)
);
CREATE TABLE IF NOT EXISTS audit_log (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, company_id BIGINT NOT NULL, actor_id BIGINT,
 action TEXT, entity_type TEXT, entity_id TEXT, details TEXT, created_at TEXT,
 PRIMARY KEY(company_id,id)
);

-- The Stage 3 ledger stores versioned tariffs, batches, tasks, work facts,
-- permissions, invoices/payments, activity/timing and finance snapshots.
-- Apply postgresql_stage3.sql separately after this core schema.
DO $$
DECLARE table_name TEXT;
BEGIN
 FOREACH table_name IN ARRAY ARRAY[
  'employees','app_users','app_sessions','portal_clients','portal_client_operations',
  'manager_client_assignments','work_log','payroll_payments','payroll_transactions',
  'client_invoices','client_payments','materials','material_movements',
  'operation_material_norms','production_jobs','production_job_progress','audit_log'
 ] LOOP
  EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', table_name);
  EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', table_name);
  EXECUTE format('DROP POLICY IF EXISTS portal_company ON %I', table_name);
  EXECUTE format(
   'CREATE POLICY portal_company ON %I USING (company_id = NULLIF(current_setting(''portal.company_id'', true),'''')::bigint) WITH CHECK (company_id = NULLIF(current_setting(''portal.company_id'', true),'''')::bigint)',
   table_name);
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = table_name || '_portal_company_fk') THEN
   EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY(company_id) REFERENCES companies(id)',
                  table_name, table_name || '_portal_company_fk');
  END IF;
 END LOOP;
END $$;

CREATE OR REPLACE FUNCTION portal_history_no_delete() RETURNS trigger
LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'financial/production history cannot be deleted'; END $$;
DO $$
DECLARE table_name TEXT;
BEGIN
 FOREACH table_name IN ARRAY ARRAY[
  'work_log','payroll_payments','payroll_transactions','client_invoices',
  'client_payments','material_movements','audit_log','platform_audit'
 ] LOOP
  EXECUTE format('DROP TRIGGER IF EXISTS portal_no_delete ON %I', table_name);
  EXECUTE format('CREATE TRIGGER portal_no_delete BEFORE DELETE ON %I FOR EACH ROW EXECUTE FUNCTION portal_history_no_delete()', table_name);
 END LOOP;
END $$;
COMMIT;
