-- Additive runtime preparation, after postgresql_core_stage4b.sql and
-- postgresql_stage3.sql. Apply with the migration owner, never the API role.
-- This migration is repeatable and fails on incompatible existing data;
-- it does not repair, delete, import or recalculate business records.
BEGIN;

-- Legacy API inserts omitted company_id because SQLite tenant files supplied
-- it as a default. PostgreSQL takes the default from the current transaction.
-- Missing context produces NULL and is rejected by NOT NULL; RLS also checks
-- explicit company_id values. The API role must not own tables or BYPASSRLS.
DO $$
DECLARE table_name TEXT;
BEGIN
 FOREACH table_name IN ARRAY ARRAY[
  'employees','app_users','app_sessions','portal_clients','portal_client_operations',
  'manager_client_assignments','work_log','payroll_payments','payroll_transactions',
  'client_invoices','client_payments','materials','material_movements',
  'operation_material_norms','production_jobs','production_job_progress','audit_log',
  'portal_production','portal_production_migrations'
 ] LOOP
  EXECUTE format(
   'ALTER TABLE %I ALTER COLUMN company_id SET DEFAULT NULLIF(current_setting(''portal.company_id'',true),'''')::bigint',
   table_name);
 END LOOP;
END $$;

ALTER TABLE materials ADD COLUMN IF NOT EXISTS min_stock NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS updated_at TEXT;

CREATE TABLE IF NOT EXISTS work_material_consumption (
 company_id BIGINT NOT NULL DEFAULT NULLIF(current_setting('portal.company_id',true),'')::bigint
  REFERENCES companies(id),
 work_id BIGINT NOT NULL,
 material_id BIGINT NOT NULL,
 quantity NUMERIC NOT NULL,
 unit_cost NUMERIC NOT NULL,
 updated_at TEXT NOT NULL,
 PRIMARY KEY(company_id,work_id,material_id),
 FOREIGN KEY(company_id,work_id) REFERENCES work_log(company_id,id),
 FOREIGN KEY(company_id,material_id) REFERENCES materials(company_id,id)
);
ALTER TABLE work_material_consumption ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_material_consumption FORCE ROW LEVEL SECURITY;
DO $$
BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_policy WHERE polrelid='work_material_consumption'::regclass AND polname='portal_company') THEN
  CREATE POLICY portal_company ON work_material_consumption
   USING (company_id = NULLIF(current_setting('portal.company_id',true),'')::bigint)
   WITH CHECK (company_id = NULLIF(current_setting('portal.company_id',true),'')::bigint);
 END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid='work_material_consumption'::regclass AND tgname='portal_no_delete') THEN
  CREATE TRIGGER portal_no_delete BEFORE DELETE ON work_material_consumption
   FOR EACH ROW EXECUTE FUNCTION portal_history_no_delete();
 END IF;
END $$;

-- New owners need generated IDs, matching the SQLite control plane. Existing
-- IDs are preserved; on first application initialize the new sequence above
-- those IDs. Subsequent runs do not rewind the sequence.
DO $$
DECLARE next_owner_id BIGINT;
BEGIN
 IF EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid='platform_owners'::regclass AND attname='id' AND attidentity='') THEN
  ALTER TABLE platform_owners ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  SELECT COALESCE(MAX(id),0)+1 INTO next_owner_id FROM platform_owners;
  EXECUTE format('ALTER TABLE platform_owners ALTER COLUMN id RESTART WITH %s',next_owner_id);
 END IF;
END $$;

-- Preserve the private control-plane boundaries of the SQLite implementation.
-- Tenant roles receive no access to platform_owners/platform_sessions/audit.
DO $$
BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='companies'::regclass AND conname='companies_runtime_values') THEN
  ALTER TABLE companies ADD CONSTRAINT companies_runtime_values CHECK (
   status IN ('active','suspended','archived')
   AND monthly_price >= 0 AND demo_enabled IN (0,1)
   AND (user_limit IS NULL OR user_limit >= 1)
   AND service_status IN ('active','suspended','expired')
   AND (id <> 1 OR user_limit IS NULL)
  );
 END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='platform_owners'::regclass AND conname='platform_owners_runtime_company_fk') THEN
  ALTER TABLE platform_owners ADD CONSTRAINT platform_owners_runtime_company_fk
   FOREIGN KEY(company_id) REFERENCES companies(id);
 END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='platform_sessions'::regclass AND conname='platform_sessions_runtime_company_fk') THEN
  ALTER TABLE platform_sessions ADD CONSTRAINT platform_sessions_runtime_company_fk
   FOREIGN KEY(company_id) REFERENCES companies(id);
 END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='platform_sessions'::regclass AND conname='platform_sessions_runtime_owner_fk') THEN
  ALTER TABLE platform_sessions ADD CONSTRAINT platform_sessions_runtime_owner_fk
   FOREIGN KEY(user_id) REFERENCES platform_owners(id);
 END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='platform_audit'::regclass AND conname='platform_audit_runtime_actor_fk') THEN
  ALTER TABLE platform_audit ADD CONSTRAINT platform_audit_runtime_actor_fk
   FOREIGN KEY(actor_id) REFERENCES platform_owners(id);
 END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid='platform_audit'::regclass AND tgname='platform_audit_no_update') THEN
  CREATE TRIGGER platform_audit_no_update BEFORE UPDATE ON platform_audit
   FOR EACH ROW EXECUTE FUNCTION portal_history_no_delete();
 END IF;
END $$;

-- SQL CHECK treats NULL as passing. Explicit presence checks close that gap
-- for JSON identities and the permanent PORTAL batch number.
DO $$
BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='portal_production'::regclass AND conname='production_runtime_identity') THEN
  ALTER TABLE portal_production ADD CONSTRAINT production_runtime_identity CHECK (
   jsonb_typeof(payload::jsonb) = 'object'
   AND (payload::jsonb ->> 'company_id') IS NOT NULL
   AND jsonb_typeof(payload::jsonb -> 'company_id') = 'number'
   AND (payload::jsonb ->> 'company_id')::bigint = company_id
   AND (payload::jsonb ->> 'id') IS NOT NULL
   AND jsonb_typeof(payload::jsonb -> 'id') = 'string'
   AND (payload::jsonb ->> 'id') = id
  );
 END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='portal_production'::regclass AND conname='production_runtime_batch_number') THEN
  ALTER TABLE portal_production ADD CONSTRAINT production_runtime_batch_number CHECK (
   kind <> 'batches' OR (
    jsonb_typeof(payload::jsonb -> 'number') = 'string'
    AND NULLIF(btrim(payload::jsonb ->> 'number'),'') IS NOT NULL
   )
  );
 END IF;
END $$;

-- An existing batch number cannot be released for reuse by changing it.
CREATE OR REPLACE FUNCTION portal_batch_number_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
 IF OLD.kind='batches' AND (OLD.payload::jsonb ->> 'number') IS DISTINCT FROM (NEW.payload::jsonb ->> 'number') THEN
  RAISE EXCEPTION 'batch number is immutable';
 END IF;
 RETURN NEW;
END;
$$;
DO $$
BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid='portal_production'::regclass AND tgname='production_batch_number_immutable') THEN
  CREATE TRIGGER production_batch_number_immutable BEFORE UPDATE ON portal_production
   FOR EACH ROW EXECUTE FUNCTION portal_batch_number_immutable();
 END IF;
END $$;

-- Global migration metadata, not tenant business data. API roles need SELECT
-- only; only the migration owner may write this table. Absence of this version
-- must stop PostgreSQL startup rather than silently selecting SQLite.
CREATE TABLE IF NOT EXISTS portal_runtime_schema (
 version INTEGER PRIMARY KEY CHECK(version > 0),
 applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO portal_runtime_schema(version) VALUES(1) ON CONFLICT(version) DO NOTHING;
COMMIT;
