-- Payroll settlement: additive, repeatable Stage 6, after protected context/Stage 5.
-- No historical employee keys, rates or closed snapshots are rewritten.
BEGIN;

CREATE TABLE IF NOT EXISTS payroll_employee_identities (
 employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
 company_id BIGINT NOT NULL DEFAULT portal_current_company(),
 legacy_employee_id BIGINT NOT NULL,
 PRIMARY KEY(company_id,employee_id),
 UNIQUE(company_id,legacy_employee_id),
 CHECK(employee_id>0),
 FOREIGN KEY(company_id) REFERENCES companies(id),
 FOREIGN KEY(company_id,legacy_employee_id) REFERENCES employees(company_id,telegram_id)
);

CREATE TABLE IF NOT EXISTS payroll_settlement_entries (
 id TEXT NOT NULL CHECK(length(id) BETWEEN 1 AND 128),
 company_id BIGINT NOT NULL DEFAULT portal_current_company(),
 employee_id BIGINT NOT NULL CHECK(employee_id>0),
 payroll_period_id TEXT NOT NULL,
 payroll_period_kind TEXT NOT NULL DEFAULT 'payroll_periods' CHECK(payroll_period_kind='payroll_periods'),
 amount_minor BIGINT NOT NULL CHECK(amount_minor <> 0 AND amount_minor BETWEEN -100000000000 AND 100000000000),
 entry_type TEXT NOT NULL CHECK(entry_type IN ('payout','adjustment','reversal')),
 effect TEXT NOT NULL CHECK(effect IN ('payment','entitlement')),
 actor_id BIGINT NOT NULL CHECK(actor_id>0),
 actor_kind TEXT NOT NULL CHECK(actor_kind IN ('user','platform_owner')),
 occurred_at TEXT NOT NULL CHECK(length(occurred_at)>0),
 reason TEXT NOT NULL CHECK(length(btrim(reason)) BETWEEN 1 AND 1000),
 reference TEXT CHECK(reference IS NULL OR length(reference)<=1000),
 request_id TEXT NOT NULL CHECK(length(request_id) BETWEEN 1 AND 128 AND request_id=btrim(request_id)),
 reversal_of TEXT,
 PRIMARY KEY(company_id,id),
 UNIQUE(company_id,request_id),
 CHECK((entry_type='payout' AND effect='payment' AND amount_minor>0 AND reversal_of IS NULL)
    OR (entry_type='adjustment' AND effect='entitlement' AND reversal_of IS NULL)
    OR (entry_type='reversal' AND reversal_of IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS payroll_settlement_period_employee
 ON payroll_settlement_entries(company_id,payroll_period_id,employee_id,occurred_at);
CREATE INDEX IF NOT EXISTS payroll_settlement_employee
 ON payroll_settlement_entries(company_id,employee_id,occurred_at);
CREATE UNIQUE INDEX IF NOT EXISTS payroll_settlement_one_reversal
 ON payroll_settlement_entries(company_id,reversal_of) WHERE reversal_of IS NOT NULL;

DO $$
BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='payroll_settlement_entries'::regclass AND conname='payroll_settlement_company_fk') THEN
  ALTER TABLE payroll_settlement_entries ADD CONSTRAINT payroll_settlement_company_fk
   FOREIGN KEY(company_id) REFERENCES companies(id);
 END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='payroll_settlement_entries'::regclass AND conname='payroll_settlement_employee_fk') THEN
  ALTER TABLE payroll_settlement_entries ADD CONSTRAINT payroll_settlement_employee_fk
   FOREIGN KEY(company_id,employee_id) REFERENCES payroll_employee_identities(company_id,employee_id);
 END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='payroll_settlement_entries'::regclass AND conname='payroll_settlement_period_fk') THEN
  ALTER TABLE payroll_settlement_entries ADD CONSTRAINT payroll_settlement_period_fk
   FOREIGN KEY(company_id,payroll_period_kind,payroll_period_id) REFERENCES portal_production(company_id,kind,id);
 END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='payroll_settlement_entries'::regclass AND conname='payroll_settlement_reversal_fk') THEN
  ALTER TABLE payroll_settlement_entries ADD CONSTRAINT payroll_settlement_reversal_fk
   FOREIGN KEY(company_id,reversal_of) REFERENCES payroll_settlement_entries(company_id,id);
 END IF;
END $$;

ALTER TABLE payroll_employee_identities ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_employee_identities FORCE ROW LEVEL SECURITY;
ALTER TABLE payroll_settlement_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_settlement_entries FORCE ROW LEVEL SECURITY;
DO $$
DECLARE t TEXT;
BEGIN
 FOREACH t IN ARRAY ARRAY['payroll_employee_identities','payroll_settlement_entries'] LOOP
  IF NOT EXISTS (SELECT 1 FROM pg_policy WHERE polrelid=t::regclass AND polname='portal_company') THEN
   EXECUTE format('CREATE POLICY portal_company ON %I USING (company_id=portal_current_company()) WITH CHECK (company_id=portal_current_company())',t);
  END IF;
 END LOOP;
END $$;

CREATE OR REPLACE FUNCTION portal_payroll_settlement_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
 RAISE EXCEPTION 'История расчётов зарплаты неизменяема';
END;
$$;

CREATE OR REPLACE FUNCTION portal_payroll_settlement_validate() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $$
DECLARE snapshot JSONB; legacy BIGINT; accrued NUMERIC; balance NUMERIC;
BEGIN
 -- Same lock as the existing company command boundary, including direct inserts.
 PERFORM pg_advisory_xact_lock(NEW.company_id);
 SELECT p.payload::jsonb INTO snapshot FROM public.portal_production p
 WHERE p.company_id=NEW.company_id AND p.kind='payroll_periods' AND p.id=NEW.payroll_period_id;
 SELECT i.legacy_employee_id INTO legacy FROM public.payroll_employee_identities i
 WHERE i.company_id=NEW.company_id AND i.employee_id=NEW.employee_id;
 IF snapshot IS NULL OR snapshot->>'status' IS DISTINCT FROM 'closed'
    OR legacy IS NULL OR NOT EXISTS (
     SELECT 1 FROM jsonb_array_elements(snapshot->'snapshot'->'employees') s
     WHERE (s->>'employee_id')::bigint=legacy) THEN
  RAISE EXCEPTION 'Сотрудник отсутствует в закрытом расчётном периоде';
 END IF;
 IF NEW.entry_type='reversal' AND NOT EXISTS (
  SELECT 1 FROM public.payroll_settlement_entries e
  WHERE e.company_id=NEW.company_id AND e.id=NEW.reversal_of
    AND e.entry_type IN ('payout','adjustment') AND e.employee_id=NEW.employee_id
    AND e.payroll_period_id=NEW.payroll_period_id AND e.effect=NEW.effect AND e.amount_minor=-NEW.amount_minor) THEN
  RAISE EXCEPTION 'Сторно должно точно компенсировать исходную запись';
 END IF;
 IF NEW.entry_type='payout' THEN
  SELECT sum((s->>'salary')::numeric) INTO accrued
  FROM jsonb_array_elements(snapshot->'snapshot'->'employees') s WHERE (s->>'employee_id')::bigint=legacy;
  SELECT accrued+coalesce(sum(CASE WHEN effect='entitlement' THEN amount_minor ELSE -amount_minor END),0)
  INTO balance FROM public.payroll_settlement_entries
  WHERE company_id=NEW.company_id AND payroll_period_id=NEW.payroll_period_id AND employee_id=NEW.employee_id;
  IF NEW.amount_minor>balance THEN
   RAISE EXCEPTION 'Сумма выплаты превышает остаток по закрытому периоду';
  END IF;
 END IF;
 RETURN NEW;
END;
$$;

DO $$
BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid='payroll_settlement_entries'::regclass AND tgname='payroll_settlement_immutable') THEN
  CREATE TRIGGER payroll_settlement_immutable BEFORE UPDATE OR DELETE ON payroll_settlement_entries
   FOR EACH ROW EXECUTE FUNCTION portal_payroll_settlement_immutable();
 END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid='payroll_settlement_entries'::regclass AND tgname='payroll_settlement_valid') THEN
  CREATE TRIGGER payroll_settlement_valid BEFORE INSERT ON payroll_settlement_entries
   FOR EACH ROW EXECUTE FUNCTION portal_payroll_settlement_validate();
 END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid='payroll_employee_identities'::regclass AND tgname='payroll_identity_immutable') THEN
  CREATE TRIGGER payroll_identity_immutable BEFORE UPDATE OR DELETE ON payroll_employee_identities
   FOR EACH ROW EXECUTE FUNCTION portal_payroll_settlement_immutable();
 END IF;
END $$;

-- Surrogate IDs for existing cards; no key is calculated from Telegram.
INSERT INTO payroll_employee_identities(company_id,legacy_employee_id)
SELECT company_id,telegram_id FROM employees
ON CONFLICT(company_id,legacy_employee_id) DO NOTHING;

INSERT INTO portal_production_migrations(company_id,version,applied_at)
SELECT id,6,CURRENT_TIMESTAMP::text FROM companies
ON CONFLICT(company_id,version) DO NOTHING;

CREATE OR REPLACE FUNCTION portal_provision_company(cid BIGINT) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$
BEGIN
 IF cid IS NULL OR cid < 1 OR NOT EXISTS(SELECT 1 FROM public.companies WHERE id=cid) THEN
  RAISE EXCEPTION 'Компания недоступна';
 END IF;
 INSERT INTO public.portal_company_keys(company_id,secret)
 VALUES(cid,encode(public.gen_random_bytes(32),'hex')) ON CONFLICT(company_id) DO NOTHING;
 INSERT INTO public.portal_production_migrations(company_id,version,applied_at)
 VALUES(cid,3,CURRENT_TIMESTAMP::text),(cid,4,CURRENT_TIMESTAMP::text),
       (cid,5,CURRENT_TIMESTAMP::text),(cid,6,CURRENT_TIMESTAMP::text)
 ON CONFLICT(company_id,version) DO NOTHING;
END;
$$;
REVOKE ALL ON FUNCTION portal_provision_company(BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION portal_payroll_settlement_validate() FROM PUBLIC;
REVOKE ALL ON FUNCTION portal_payroll_settlement_immutable() FROM PUBLIC;

COMMIT;
