-- PORTAL PostgreSQL Stage 4C
-- Compatibility layer for the verified real Android SQLite database.
-- Source inventory: read-only copy portal_phone_20260926.db.
-- This migration must be reviewed and tested only on an isolated database first.
--
-- Goals:
-- 1. Preserve legacy business tables still used by the live Telegram bot.
-- 2. Preserve legacy columns missing from the Stage 4B PostgreSQL core.
-- 3. Add company_id isolation and FORCE RLS before any production use.
-- 4. Preserve financial and production history without rewriting source data.

BEGIN;

-- Stage 4C blocks are added below after schema verification.

CREATE TABLE IF NOT EXISTS products (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY,
 company_id BIGINT NOT NULL,
 client TEXT NOT NULL,
 name TEXT NOT NULL,
 material_cost_per_unit NUMERIC NOT NULL DEFAULT 0,
 other_cost_per_unit NUMERIC NOT NULL DEFAULT 0,
 active INTEGER NOT NULL DEFAULT 1,
 created_at TEXT NOT NULL,
 PRIMARY KEY(company_id,id),
 UNIQUE(company_id,client,name),
 FOREIGN KEY(company_id) REFERENCES companies(id)
);

CREATE TABLE IF NOT EXISTS tariff_versions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY,
 company_id BIGINT NOT NULL,
 client TEXT NOT NULL,
 operation TEXT NOT NULL,
 employee_rate NUMERIC,
 client_rate NUMERIC,
 valid_from TEXT NOT NULL,
 valid_to TEXT,
 created_by BIGINT,
 created_at TEXT NOT NULL,
 PRIMARY KEY(company_id,id),
 FOREIGN KEY(company_id) REFERENCES companies(id)
);
CREATE INDEX IF NOT EXISTS idx_tariff_active
 ON tariff_versions (company_id,client,operation,valid_to,valid_from);

CREATE TABLE IF NOT EXISTS portal_manager_service_rates (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY,
 company_id BIGINT NOT NULL,
 client_id BIGINT NOT NULL,
 service_code TEXT NOT NULL,
 service_name TEXT NOT NULL,
 unit TEXT NOT NULL DEFAULT 'шт.',
 price NUMERIC,
 active INTEGER NOT NULL DEFAULT 1,
 updated_at TEXT NOT NULL,
 updated_by BIGINT,
 PRIMARY KEY(company_id,id),
 UNIQUE(company_id,client_id,service_code),
 FOREIGN KEY(company_id,client_id) REFERENCES portal_clients(company_id,id)
);
CREATE INDEX IF NOT EXISTS idx_manager_service_rates_client
 ON portal_manager_service_rates (company_id,client_id,active,service_code);

-- Access, roles and invitation state from the live bot.
CREATE TABLE IF NOT EXISTS managers (
 company_id BIGINT NOT NULL,
 telegram_id BIGINT NOT NULL,
 full_name TEXT NOT NULL,
 username TEXT,
 added_at TEXT NOT NULL,
 added_by BIGINT NOT NULL,
 active INTEGER NOT NULL DEFAULT 1,
 PRIMARY KEY(company_id,telegram_id),
 FOREIGN KEY(company_id) REFERENCES companies(id)
);

CREATE TABLE IF NOT EXISTS employee_invites (
 company_id BIGINT NOT NULL,
 token TEXT NOT NULL,
 created_by BIGINT NOT NULL,
 created_at TEXT NOT NULL,
 expires_at TEXT NOT NULL,
 max_uses BIGINT NOT NULL DEFAULT 1,
 uses BIGINT NOT NULL DEFAULT 0,
 active INTEGER NOT NULL DEFAULT 1,
 used_by BIGINT,
 used_at TEXT,
 PRIMARY KEY(company_id,token),
 FOREIGN KEY(company_id) REFERENCES companies(id)
);

CREATE TABLE IF NOT EXISTS employee_access_requests (
 company_id BIGINT NOT NULL,
 telegram_id BIGINT NOT NULL,
 full_name TEXT,
 username TEXT,
 status TEXT NOT NULL DEFAULT 'pending',
 requested_at TEXT NOT NULL,
 decided_at TEXT,
 decided_by BIGINT,
 registered_at TEXT,
 PRIMARY KEY(company_id,telegram_id),
 FOREIGN KEY(company_id) REFERENCES companies(id)
);
CREATE INDEX IF NOT EXISTS idx_employee_access_requests_status
 ON employee_access_requests(company_id,status,requested_at);

CREATE TABLE IF NOT EXISTS client_access (
 company_id BIGINT NOT NULL,
 telegram_id BIGINT NOT NULL,
 client TEXT NOT NULL,
 full_name TEXT,
 username TEXT,
 active INTEGER NOT NULL DEFAULT 1,
 linked_at TEXT NOT NULL,
 PRIMARY KEY(company_id,telegram_id),
 FOREIGN KEY(company_id) REFERENCES companies(id)
);

CREATE TABLE IF NOT EXISTS user_roles (
 company_id BIGINT NOT NULL,
 telegram_id BIGINT NOT NULL,
 role TEXT NOT NULL,
 granted_by BIGINT NOT NULL,
 granted_at TEXT NOT NULL,
 active INTEGER NOT NULL DEFAULT 1,
 revoked_at TEXT,
 PRIMARY KEY(company_id,telegram_id,role),
 FOREIGN KEY(company_id) REFERENCES companies(id)
);
CREATE INDEX IF NOT EXISTS idx_user_roles_role
 ON user_roles(company_id,role,active);

CREATE TABLE IF NOT EXISTS client_permissions (
 company_id BIGINT NOT NULL,
 telegram_id BIGINT NOT NULL,
 can_view_work INTEGER NOT NULL DEFAULT 1,
 can_view_invoices INTEGER NOT NULL DEFAULT 1,
 can_view_payments INTEGER NOT NULL DEFAULT 1,
 can_download_report INTEGER NOT NULL DEFAULT 1,
 updated_at TEXT NOT NULL,
 updated_by BIGINT,
 PRIMARY KEY(company_id,telegram_id),
 FOREIGN KEY(company_id) REFERENCES companies(id)
);

CREATE TABLE IF NOT EXISTS client_invites (
 company_id BIGINT NOT NULL,
 code TEXT NOT NULL,
 client TEXT NOT NULL,
 created_by BIGINT NOT NULL,
 created_at TEXT NOT NULL,
 used_at TEXT,
 used_by BIGINT,
 active INTEGER NOT NULL DEFAULT 1,
 PRIMARY KEY(company_id,code),
 FOREIGN KEY(company_id) REFERENCES companies(id)
);

CREATE TABLE IF NOT EXISTS client_name_overrides (
 company_id BIGINT NOT NULL,
 canonical_name TEXT NOT NULL,
 current_name TEXT NOT NULL,
 updated_at TEXT NOT NULL,
 updated_by BIGINT,
 PRIMARY KEY(company_id,canonical_name),
 UNIQUE(company_id,current_name),
 FOREIGN KEY(company_id) REFERENCES companies(id)
);

-- Employee internal chat.
CREATE TABLE IF NOT EXISTS employee_chat_messages (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY,
 company_id BIGINT NOT NULL,
 telegram_id BIGINT NOT NULL,
 full_name TEXT NOT NULL,
 message_type TEXT NOT NULL DEFAULT 'text',
 text TEXT,
 file_id TEXT,
 created_at TEXT NOT NULL,
 PRIMARY KEY(company_id,id),
 FOREIGN KEY(company_id) REFERENCES companies(id)
);
CREATE INDEX IF NOT EXISTS idx_employee_chat_messages_created
 ON employee_chat_messages(company_id,created_at);

CREATE TABLE IF NOT EXISTS employee_chat_settings (
 company_id BIGINT NOT NULL,
 telegram_id BIGINT NOT NULL,
 notifications_enabled INTEGER NOT NULL DEFAULT 1,
 updated_at TEXT NOT NULL,
 PRIMARY KEY(company_id,telegram_id),
 FOREIGN KEY(company_id) REFERENCES companies(id)
);

-- Complete the Stage 4B invoice/payment schema with live-bot fields.
ALTER TABLE client_invoices ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE client_invoices ADD COLUMN IF NOT EXISTS updated_at TEXT;
ALTER TABLE client_invoices ADD COLUMN IF NOT EXISTS seller_requisites_json TEXT;
ALTER TABLE client_invoices ADD COLUMN IF NOT EXISTS buyer_requisites_json TEXT;
ALTER TABLE client_invoices ADD COLUMN IF NOT EXISTS document_build TEXT;

ALTER TABLE client_payments ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE client_payments ADD COLUMN IF NOT EXISTS paid_at TEXT;
ALTER TABLE client_payments ADD COLUMN IF NOT EXISTS recorded_by BIGINT;
ALTER TABLE client_payments ADD COLUMN IF NOT EXISTS note TEXT;

CREATE TABLE IF NOT EXISTS client_invoice_items (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY,
 company_id BIGINT NOT NULL,
 invoice_id BIGINT NOT NULL,
 service_code TEXT NOT NULL,
 service_name TEXT NOT NULL,
 unit TEXT NOT NULL,
 quantity NUMERIC NOT NULL,
 unit_price NUMERIC NOT NULL,
 amount NUMERIC NOT NULL,
 created_at TEXT NOT NULL,
 PRIMARY KEY(company_id,id),
 FOREIGN KEY(company_id,invoice_id) REFERENCES client_invoices(company_id,id)
);
CREATE INDEX IF NOT EXISTS idx_client_invoice_items_invoice
 ON client_invoice_items(company_id,invoice_id,id);

CREATE TABLE IF NOT EXISTS portal_company_requisites (
 company_id BIGINT NOT NULL,
 id BIGINT NOT NULL,
 legal_name TEXT,
 inn TEXT,
 kpp TEXT,
 ogrn TEXT,
 legal_address TEXT,
 settlement_account TEXT,
 bank_name TEXT,
 bik TEXT,
 correspondent_account TEXT,
 phone TEXT,
 email TEXT,
 director TEXT,
 tax_info TEXT,
 updated_at TEXT NOT NULL,
 updated_by BIGINT,
 PRIMARY KEY(company_id,id),
 CHECK(id=1),
 FOREIGN KEY(company_id) REFERENCES companies(id)
);

CREATE TABLE IF NOT EXISTS portal_client_requisites (
 company_id BIGINT NOT NULL,
 client_id BIGINT NOT NULL,
 legal_name TEXT,
 inn TEXT,
 kpp TEXT,
 ogrn TEXT,
 legal_address TEXT,
 settlement_account TEXT,
 bank_name TEXT,
 bik TEXT,
 correspondent_account TEXT,
 phone TEXT,
 email TEXT,
 contact_person TEXT,
 tax_info TEXT,
 updated_at TEXT NOT NULL,
 updated_by BIGINT,
 PRIMARY KEY(company_id,client_id),
 FOREIGN KEY(company_id,client_id) REFERENCES portal_clients(company_id,id)
);

-- Operational state and histories still used by the live bot.
CREATE TABLE IF NOT EXISTS expense_requests (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY,
 company_id BIGINT NOT NULL,
 requester_id BIGINT NOT NULL,
 requester_name TEXT NOT NULL,
 client TEXT,
 product_id BIGINT,
 description TEXT NOT NULL,
 amount NUMERIC NOT NULL,
 status TEXT NOT NULL DEFAULT 'pending',
 requested_at TEXT NOT NULL,
 decided_at TEXT,
 decided_by BIGINT,
 note TEXT,
 category TEXT,
 PRIMARY KEY(company_id,id),
 FOREIGN KEY(company_id) REFERENCES companies(id)
);
CREATE INDEX IF NOT EXISTS idx_expense_status
 ON expense_requests(company_id,status,requested_at);

CREATE TABLE IF NOT EXISTS scheduled_runs (
 company_id BIGINT NOT NULL,
 run_key TEXT NOT NULL,
 run_at TEXT NOT NULL,
 PRIMARY KEY(company_id,run_key),
 FOREIGN KEY(company_id) REFERENCES companies(id)
);

CREATE TABLE IF NOT EXISTS marketplace_news (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY,
 company_id BIGINT NOT NULL,
 source TEXT NOT NULL,
 title TEXT NOT NULL,
 body TEXT NOT NULL,
 url TEXT NOT NULL,
 published_at TEXT,
 fetched_at TEXT NOT NULL,
 is_regulation INTEGER NOT NULL DEFAULT 0,
 external_key TEXT NOT NULL,
 PRIMARY KEY(company_id,id),
 UNIQUE(company_id,external_key),
 FOREIGN KEY(company_id) REFERENCES companies(id)
);
CREATE INDEX IF NOT EXISTS idx_marketplace_news_source_date
 ON marketplace_news(company_id,source,published_at DESC,id DESC);
CREATE INDEX IF NOT EXISTS idx_marketplace_news_regulation
 ON marketplace_news(company_id,is_regulation,published_at DESC,id DESC);

CREATE TABLE IF NOT EXISTS backup_log (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY,
 company_id BIGINT NOT NULL,
 file_path TEXT NOT NULL,
 size_bytes BIGINT NOT NULL,
 created_at TEXT NOT NULL,
 PRIMARY KEY(company_id,id),
 FOREIGN KEY(company_id) REFERENCES companies(id)
);

CREATE TABLE IF NOT EXISTS system_settings (
 company_id BIGINT NOT NULL,
 key TEXT NOT NULL,
 value TEXT NOT NULL,
 updated_at TEXT NOT NULL,
 PRIMARY KEY(company_id,key),
 FOREIGN KEY(company_id) REFERENCES companies(id)
);

CREATE TABLE IF NOT EXISTS production_job_assignments (
 company_id BIGINT NOT NULL,
 job_id BIGINT NOT NULL,
 telegram_id BIGINT NOT NULL,
 status TEXT NOT NULL DEFAULT 'assigned',
 assigned_at TEXT NOT NULL,
 completed_at TEXT,
 PRIMARY KEY(company_id,job_id,telegram_id),
 FOREIGN KEY(company_id,job_id) REFERENCES production_jobs(company_id,id)
);

CREATE TABLE IF NOT EXISTS payroll_closure_batches (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY,
 company_id BIGINT NOT NULL,
 period_start TEXT NOT NULL,
 period_end TEXT NOT NULL,
 employees_total BIGINT NOT NULL DEFAULT 0,
 employees_closed BIGINT NOT NULL DEFAULT 0,
 amount_paid NUMERIC NOT NULL DEFAULT 0,
 statement_path TEXT,
 created_by BIGINT NOT NULL,
 created_at TEXT NOT NULL,
 PRIMARY KEY(company_id,id),
 FOREIGN KEY(company_id) REFERENCES companies(id)
);

-- Legacy columns required for lossless import of the verified phone database.
ALTER TABLE employees ADD COLUMN IF NOT EXISTS registered_at TEXT;
ALTER TABLE manager_client_assignments ADD COLUMN IF NOT EXISTS assigned_at TEXT;
ALTER TABLE manager_client_assignments ADD COLUMN IF NOT EXISTS assigned_by BIGINT;

ALTER TABLE materials ADD COLUMN IF NOT EXISTS created_at TEXT;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE operation_material_norms ADD COLUMN IF NOT EXISTS created_at TEXT;
ALTER TABLE operation_material_norms ADD COLUMN IF NOT EXISTS updated_at TEXT;
ALTER TABLE operation_material_norms ADD COLUMN IF NOT EXISTS updated_by BIGINT;

ALTER TABLE payroll_payments ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE payroll_payments ADD COLUMN IF NOT EXISTS quantity_snapshot NUMERIC;
ALTER TABLE payroll_payments ADD COLUMN IF NOT EXISTS amount_snapshot NUMERIC;
ALTER TABLE payroll_payments ADD COLUMN IF NOT EXISTS paid_at TEXT;

ALTER TABLE payroll_transactions ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE payroll_transactions ADD COLUMN IF NOT EXISTS paid_at TEXT;
ALTER TABLE payroll_transactions ADD COLUMN IF NOT EXISTS note TEXT;

ALTER TABLE portal_clients ADD COLUMN IF NOT EXISTS source TEXT;
ALTER TABLE portal_clients ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE portal_client_operations ADD COLUMN IF NOT EXISTS source TEXT;
ALTER TABLE portal_client_operations ADD COLUMN IF NOT EXISTS created_by BIGINT;

ALTER TABLE production_jobs ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE production_jobs ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE production_jobs ADD COLUMN IF NOT EXISTS created_at TEXT;
ALTER TABLE production_job_progress ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE work_log ADD COLUMN IF NOT EXISTS product_id BIGINT;
ALTER TABLE work_log ADD COLUMN IF NOT EXISTS product_name TEXT;
ALTER TABLE work_log ADD COLUMN IF NOT EXISTS unit_direct_cost NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE work_log ADD COLUMN IF NOT EXISTS tariff_version_id BIGINT;
ALTER TABLE work_log ADD COLUMN IF NOT EXISTS anomaly_flag INTEGER NOT NULL DEFAULT 0;

-- Enforce tenant isolation on every Stage 4C table.
DO $$
DECLARE t TEXT;
BEGIN
 FOREACH t IN ARRAY ARRAY[
  'backup_log','client_access','client_invites','client_invoice_items',
  'client_name_overrides','client_permissions','employee_access_requests',
  'employee_chat_messages','employee_chat_settings','employee_invites',
  'expense_requests','managers','marketplace_news','payroll_closure_batches',
  'portal_client_requisites','portal_company_requisites',
  'portal_manager_service_rates','production_job_assignments','products',
  'scheduled_runs','system_settings','tariff_versions','user_roles'
 ] LOOP
  EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t);
  EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',t);
  EXECUTE format('DROP POLICY IF EXISTS portal_company ON %I',t);
  EXECUTE format(
   'CREATE POLICY portal_company ON %I USING (company_id = portal_current_company()) WITH CHECK (company_id = portal_current_company())',
   t
  );
 END LOOP;
END $$;

COMMIT;
